codecov:
  branch: master

coverage:

  notify:
    gitter:
      default:
        url: https://gitter.im/Syncleus/Ferma
        threshold: 50

    webhook:
      default:
        url: https://webhooks.gitter.im/e/ca09ab5b83c9439518b0
