site_name: Ferma
theme: material
repo_name: 'GitHub'
repo_url: 'https://github.com/Syncleus/Ferma'
site_dir: 'target/mkdocs'
pages:
    - Home: index.md
    - Getting Started: getting_started.md
    - Comparing the Alternatives: comparing_the_alternatives.md
    - Glossary: glossary.md
    - Core Annotations:
        - Overview: annotations/overview.md
        - '@Property': annotations/property.md
        - '@adjacency': annotations/adjacency.md
extra:
  version: '3.0.1'
  logo: 'images/ferma-logo.svg'
  github:
    download_release: true
  palette:
    primary: 'blue'
    accent: 'deep orange'
  author:
    github: 'Syncleus'

markdown_extensions:
  - codehilite(css_class=code)
  - admonition
  - toc:
      permalink: '#'
